export const EMAIL_AUTH_SIGNUP_REQUEST = "EMAIL_AUTH_SIGNUP_REQUEST";
export const EMAIL_AUTH_SIGNUP_SUCCESS = "EMAIL_AUTH_SIGNUP_SUCCESS";
export const EMAIL_AUTH_SIGNUP_ERROR = "EMAIL_AUTH_SIGNUP_ERROR";

export const EMAIL_AUTH_LOGIN_REQUEST = "EMAIL_AUTH_LOGIN_REQUEST";
export const EMAIL_AUTH_LOGIN_SUCCESS = "EMAIL_AUTH_LOGIN_SUCCESS";
export const EMAIL_AUTH_LOGIN_ERROR = "EMAIL_AUTH_LOGIN_ERROR";

export const EMAIL_AUTH_LOGOUT = "EMAIL_AUTH_LOGOUT";

export const EMAIL_AUTH_PASSWORD_RECOVER_REQUEST =
  "EMAIL_AUTH_PASSORD_RECOVER_REQUEST";
export const EMAIL_AUTH_PASSWORD_RECOVER_SUCCESS =
  "EMAIL_AUTH_PASSORD_RECOVER_SUCCESS";
export const EMAIL_AUTH_PASSWORD_RECOVER_ERROR =
  "EMAIL_AUTH_PASSORD_RECOVER_ERROR";